### ISSUE TITLE
Use huh for the server command user input

### ISSUE THREAD

**Issue by bsach64** [bsach64/goback#23]
huh is a library by the bubbletea guys for terminal forms

Read this tutorial for huh:
https://github.com/charmbracelet/huh?tab=readme-ov-file#tutorial

use
`go get https://github.com/charmbracelet/huh` to install huh

modify
`cmd/server.go`

**Comment by omdiwan06** [comment]
okay, on it.

**Comment by omdiwan06** [comment]
Completed. #25
